In [1]:
import pandas as pd

In [2]:
a=pd.read_csv("kd.csv")

In [3]:
a.describe()

,version,size(bytes),downloads,discussions,views,likes,kernels
count,18518.000000,1.851800e+04,18518.000000,18518.000000,1.851800e+04,18518.000000,18518.000000
mean,5.460471,4.204281e+09,394.869424,0.287882,3.083455e+03,9.816233,6.004752
std,23.842488,4.230264e+11,2673.503306,1.705490,2.792698e+04,62.888877,56.726649
min,1.000000,2.200000e+01,0.000000,0.000000,2.000000e+00,0.000000,0.000000
25%,1.000000,4.013425e+04,6.000000,0.000000,1.240000e+02,0.000000,1.000000
50%,1.000000,1.101386e+06,21.000000,0.000000,3.270000e+02,0.000000,1.000000
75%,1.000000,4.472701e+07,98.000000,0.000000,9.720000e+02,3.000000,2.000000
max,370.000000,5.736049e+13,131731.000000,95.000000,3.052086e+06,3323.000000,3810.000000

In [4]:
a.head()

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
0,mlg-ulb/creditcardfraud,Credit Card Fraud Detection,Anonymized credit card transactions labeled as...,Machine Learning Group - ULB,Context\n---------\n\nIt is important that cre...,3,"finance, machine learning, crime",2018-03-23 01:17:27,"Database: Open Database, Contents: Database Co...",66MB,69155632,131731,40,3052086,3323,2121
1,tmdb/tmdb-movie-metadata,TMDB 5000 Movie Dataset,"Metadata on ~5,000 movies from TMDb",The Movie Database (TMDb),### Background\nWhat can we say about the succ...,2,film,2017-09-28 01:09:12,Other (specified in description),9MB,9747156,92202,53,630515,1601,1462
2,hugomathien/soccer,European Soccer Database,"25k+ matches, players & teams attributes for E...",Hugo Mathien,The ultimate Soccer database for data analysis...,10,"europe, association football",2016-10-23 22:31:38,"Database: Open Database, Contents: Â© Original ...",34MB,36121187,80922,95,638231,1875,1458
3,lava18/google-play-store-apps,Google Play Store Apps,Web scraped data of 10k Play Store apps for an...,Lavanya Gupta,### Context\n\nWhile many public datasets (on ...,6,"internet, video games, computer science, mobil...",2019-02-03 13:55:47,Unknown,2MB,2013348,72020,37,440983,1861,313
4,zynicide/wine-reviews,Wine Reviews,"130k wine reviews with variety, location, wine...",zackthoutt,### Context\n\nAfter watching [Somm](http://ww...,4,"food and drink, critical theory",2017-11-27 17:08:04,CC BY-NC-SA 4.0,51MB,53336173,68002,24,342243,1609,1948

In [5]:
a.head(13)

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
0,mlg-ulb/creditcardfraud,Credit Card Fraud Detection,Anonymized credit card transactions labeled as...,Machine Learning Group - ULB,Context\n---------\n\nIt is important that cre...,3,"finance, machine learning, crime",2018-03-23 01:17:27,"Database: Open Database, Contents: Database Co...",66MB,69155632,131731,40,3052086,3323,2121
1,tmdb/tmdb-movie-metadata,TMDB 5000 Movie Dataset,"Metadata on ~5,000 movies from TMDb",The Movie Database (TMDb),### Background\nWhat can we say about the succ...,2,film,2017-09-28 01:09:12,Other (specified in description),9MB,9747156,92202,53,630515,1601,1462
2,hugomathien/soccer,European Soccer Database,"25k+ matches, players & teams attributes for E...",Hugo Mathien,The ultimate Soccer database for data analysis...,10,"europe, association football",2016-10-23 22:31:38,"Database: Open Database, Contents: Â© Original ...",34MB,36121187,80922,95,638231,1875,1458
3,lava18/google-play-store-apps,Google Play Store Apps,Web scraped data of 10k Play Store apps for an...,Lavanya Gupta,### Context\n\nWhile many public datasets (on ...,6,"internet, video games, computer science, mobil...",2019-02-03 13:55:47,Unknown,2MB,2013348,72020,37,440983,1861,313
4,zynicide/wine-reviews,Wine Reviews,"130k wine reviews with variety, location, wine...",zackthoutt,### Context\n\nAfter watching [Somm](http://ww...,4,"food and drink, critical theory",2017-11-27 17:08:04,CC BY-NC-SA 4.0,51MB,53336173,68002,24,342243,1609,1948
5,ronitf/heart-disease-uci,Heart Disease UCI,https://archive.ics.uci.edu/ml/datasets/Heart+...,ronit,### Context \n\nThis database contains 76 attr...,1,"classification, binary classification, health,...",2018-06-25 11:33:56,Reddit API Terms,3KB,3438,67832,41,404892,2161,625
6,unsdsn/world-happiness,World Happiness Report,Happiness scored according to economic product...,Sustainable Development Solutions Network,### Context \n\nThe World Happiness Report is ...,2,"economics, social sciences, emotion",2017-06-14 20:41:45,CC0: Public Domain,29KB,29425,67658,6,273284,976,461
7,uciml/iris,Iris Species,Classify iris plants into three species in thi...,UCI Machine Learning,The Iris dataset was used in R.A. Fisher's cla...,2,botany,2016-09-27 07:38:05,CC0: Public Domain,4KB,3718,65859,18,292620,984,3810
8,wendykan/lending-club-loan-data,Lending Club Loan Data,Analyze Lending Club's issued loans,Wendy Kan,These files contain complete loan data for all...,1,finance,2019-03-18 18:43:12,Unknown,702MB,736483000,52096,33,293239,953,582
9,uciml/breast-cancer-wisconsin-data,Breast Cancer Wisconsin (Diagnostic) Data Set,Predict whether the cancer is benign or malignant,UCI Machine Learning,Features are computed from a digitized image o...,2,healthcare,2016-09-25 10:49:04,CC BY-NC-SA 4.0,48KB,49196,51767,22,321503,837,862
10,uciml/pima-indians-diabetes-database,Pima Indians Diabetes Database,Predict the onset of diabetes based on diagnos...,UCI Machine Learning,## Context\n\nThis dataset is originally from ...,1,"healthcare, india, health sciences",2016-10-06 18:31:56,CC0: Public Domain,9KB,9077,51210,11,268744,601,599
11,mehdidag/black-friday,Black Friday,A study of sales trough consumer behaviours,Mehdi Dagdoug,## Description\n\nThe dataset here is a sample...,1,"business, regression analysis",2018-07-25 20:49:48,CC0: Public Domain,5MB,5621145,49935,28,327920,1230,202
12,russellyates88/suicide-rates-overview-1985-to-...,Suicide Rates Overview 1985 to 2016,Compares socio-economic info with suicide rate...,Rusty,### Content\n\nThis compiled dataset pulled fr...,1,"economics, demographics, world",2018-12-01 19:18:25,World Bank Dataset Terms of Use,396KB,405202,47317,15,243420,1285,200

In [6]:
a.tail(9)

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
18509,alexfraze/popular-embeddings,popular_embeddings,NaN,Alex Frazier,# Dataset\nThis dataset was created by Alex Fr...,1,NaN,2019-03-27 16:43:27,Unknown,6GB,6395920052,0,0,38,0,1
18510,zefangzhou/752754217,089030,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,2,NaN,2019-04-01 03:31:03,Unknown,1MB,1347412,0,0,34,0,1
18511,zefangzhou/t08894,t08894,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,6,NaN,2019-04-09 10:40:20,Unknown,1MB,1470247,0,0,41,0,1
18512,nguyentranthanhphuc/eiu-220-95448,EIU_220_95448,bert-vanila-cont-from-220-95734,Phuc Nguyen,# Dataset\nThis dataset was created by Phuc Ng...,1,NaN,2019-06-16 03:01:24,Unknown,775MB,812775564,0,0,12,0,1
18513,charalambos/sample-2,sample 2,NaN,Charalambos Stamatis,# Dataset\nThis dataset was created by Charala...,1,NaN,2019-03-28 15:56:22,Unknown,1MB,1272752,0,0,25,0,1
18514,zefangzhou/zfsouyou,zfsouyou,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,1,NaN,2019-03-28 12:02:37,Unknown,5MB,5635067,0,0,30,0,1
18515,zefangzhou/089271,089271,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,4,NaN,2019-04-07 02:14:42,Unknown,1MB,1307950,0,0,27,0,1
18516,bettinajohn/python-ml-ch03-images,Python_ML_Ch03_images,Images for WIDS-Atx presentation on Chapter 3 ...,Bettina,# Dataset\nThis dataset was created by Bettina...,1,NaN,2019-03-28 02:13:20,Unknown,4MB,3730135,0,0,27,0,2
18517,pramod722445/abcde16,abcde16,NaN,pramod,# Dataset\nThis dataset was created by pramod\...,1,NaN,2019-05-28 19:19:32,Unknown,2GB,2604593950,0,0,13,0,1

In [7]:
a.tail()

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
18513,charalambos/sample-2,sample 2,NaN,Charalambos Stamatis,# Dataset\nThis dataset was created by Charala...,1,NaN,2019-03-28 15:56:22,Unknown,1MB,1272752,0,0,25,0,1
18514,zefangzhou/zfsouyou,zfsouyou,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,1,NaN,2019-03-28 12:02:37,Unknown,5MB,5635067,0,0,30,0,1
18515,zefangzhou/089271,089271,NaN,fang,# Dataset\nThis dataset was created by fang\n\...,4,NaN,2019-04-07 02:14:42,Unknown,1MB,1307950,0,0,27,0,1
18516,bettinajohn/python-ml-ch03-images,Python_ML_Ch03_images,Images for WIDS-Atx presentation on Chapter 3 ...,Bettina,# Dataset\nThis dataset was created by Bettina...,1,NaN,2019-03-28 02:13:20,Unknown,4MB,3730135,0,0,27,0,2
18517,pramod722445/abcde16,abcde16,NaN,pramod,# Dataset\nThis dataset was created by pramod\...,1,NaN,2019-05-28 19:19:32,Unknown,2GB,2604593950,0,0,13,0,1

In [8]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18518 entries, 0 to 18517
Data columns (total 16 columns):
ref             18518 non-null object
title           18518 non-null object
subtitle        8012 non-null object
creator         18515 non-null object
description     18518 non-null object
version         18518 non-null int64
keywords        5677 non-null object
last_updated    18518 non-null object
license_name    18518 non-null object
size            18518 non-null object
size(bytes)     18518 non-null int64
downloads       18518 non-null int64
discussions     18518 non-null int64
views           18518 non-null int64
likes           18518 non-null int64
kernels         18518 non-null int64
dtypes: int64(7), object(9)
memory usage: 2.3+ MB

In [9]:
a.dtypes

ref             object
title           object
subtitle        object
creator         object
description     object
version          int64
keywords        object
last_updated    object
license_name    object
size            object
size(bytes)      int64
downloads        int64
discussions      int64
views            int64
likes            int64
kernels          int64
dtype: object

In [10]:
a.sort_values("version")

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
9258,melodydreamj/imagenet-file,imageNet_file,NaN,june lee,# Dataset\nThis dataset was created by june le...,1,NaN,2018-06-02 14:23:13,CC0: Public Domain,7MB,7620392,21,0,430,0,0
11966,sachin619/got-battle-of-blackwater,GOT_battle_of_blackwater,got battle (prediction),sachin,# Dataset\nThis dataset was created by sachin\...,1,regression,2019-03-08 18:54:35,Unknown,137MB,143571271,10,0,176,0,2
11969,msbrvamsi/population-country-wise-from-since-2...,Population country wise since 2002 till 2016,NaN,msbrvamsi,# Dataset\nThis dataset was created by msbrvam...,1,NaN,2018-10-16 12:53:23,World Bank Dataset Terms of Use,248KB,253889,10,0,153,0,1
11970,kuroski/medicalappointmentnoshown,medical-appointment-no-shown,NaN,Kuroski,# Dataset\nThis dataset was created by Kuroski...,1,NaN,2019-04-05 20:24:52,Unknown,2MB,2490670,10,0,49,0,2
11971,thaikeras/vsb-wavelet-denoised,VSB_Wavelet_Denoised,a denoised version of signals in the VSB parti...,ThaiKeras,### Context\n\nRegarding VSB partial fault det...,1,signal data,2019-03-25 05:24:54,Unknown,600MB,629307956,10,1,180,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4579,theworldbank/contributions-to-financial-interm...,Contributions to Financial Intermediary Funds,From World Bank Financial Open Data,World Bank,### Content \n\nFinancial Intermediary Funds (...,369,socrata,2019-07-06 14:09:37,CC0: Public Domain,46KB,47493,100,0,1693,3,1
12525,theworldbank/ibrd-summary-of-allocable-income,IBRD Summary of Allocable Income,From World Bank Financial Open Data,World Bank,### Content \n\nProvides summary of allocable ...,370,socrata,2019-07-06 14:09:50,CC0: Public Domain,3KB,3142,9,0,450,0,1
8548,theworldbank/commercial-credit-exposure-by-cou...,Commercial Credit Exposure by Counterparty Rating,From World Bank Financial Open Data,World Bank,### Content \n\nProvides data on investment co...,370,socrata,2019-07-06 14:09:35,CC0: Public Domain,3KB,3464,26,0,535,0,1
11499,theworldbank/ida-voting-power-of-member-countries,IDA Voting Power of Member Countries,From World Bank Financial Open Data,World Bank,### Content \n\nMember countries are allocated...,370,socrata,2019-07-06 14:09:52,CC0: Public Domain,5KB,5440,11,0,325,0,1
10111,theworldbank/miga-summary-income-statement,MIGA Summary Income Statement,From World Bank Financial Open Data,World Bank,### Content \n\nProvides summary income statem...,370,socrata,2019-07-06 14:10:17,CC0: Public Domain,3KB,2603,17,0,515,1,1

In [11]:
a.sort_values("version").head(10)

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
9258,melodydreamj/imagenet-file,imageNet_file,NaN,june lee,# Dataset\nThis dataset was created by june le...,1,NaN,2018-06-02 14:23:13,CC0: Public Domain,7MB,7620392,21,0,430,0,0
11966,sachin619/got-battle-of-blackwater,GOT_battle_of_blackwater,got battle (prediction),sachin,# Dataset\nThis dataset was created by sachin\...,1,regression,2019-03-08 18:54:35,Unknown,137MB,143571271,10,0,176,0,2
11969,msbrvamsi/population-country-wise-from-since-2...,Population country wise since 2002 till 2016,NaN,msbrvamsi,# Dataset\nThis dataset was created by msbrvam...,1,NaN,2018-10-16 12:53:23,World Bank Dataset Terms of Use,248KB,253889,10,0,153,0,1
11970,kuroski/medicalappointmentnoshown,medical-appointment-no-shown,NaN,Kuroski,# Dataset\nThis dataset was created by Kuroski...,1,NaN,2019-04-05 20:24:52,Unknown,2MB,2490670,10,0,49,0,2
11971,thaikeras/vsb-wavelet-denoised,VSB_Wavelet_Denoised,a denoised version of signals in the VSB parti...,ThaiKeras,### Context\n\nRegarding VSB partial fault det...,1,signal data,2019-03-25 05:24:54,Unknown,600MB,629307956,10,1,180,2,3
11972,isamuisozaki/roughly-one-quarter-of-openwebtext,Roughly one quarter of openwebtext,This is a quarter of the open webtext data,Isamu,### Context\n\nThis is a dataset made by modif...,1,reddit,2019-05-05 00:52:25,Attribution 4.0 International (CC BY 4.0),3GB,3436317368,10,1,157,0,1
11973,ykatayama/180111-01,180111_01,NaN,ykatayama,# Dataset\nThis dataset was created by ykataya...,1,NaN,2018-01-11 07:50:09,Data files Â© Original Authors,8MB,8071105,10,0,324,0,0
11977,idasorndal/42156-english-website,42156 English Website,You can use it as you like.,Ida SÃ¶rndal,### About sites\n\nAll the sites were obtained...,1,"internet, web sites",2018-07-10 02:31:21,Unknown,359KB,367787,10,0,471,0,0
11978,daniel012/pokemon,Pokemon,NaN,Hyungjin_Jeon,# Dataset\nThis dataset was created by Hyungji...,1,NaN,2019-03-15 05:00:25,Data files Â© Original Authors,280KB,286223,10,0,105,0,2
11979,adri91186/extradata,extradata,NaN,AdriÃ¡n Cavaiuolo,# Dataset\nThis dataset was created by AdriÃ¡n ...,1,NaN,2018-04-16 06:41:38,CC0: Public Domain,2KB,2061,10,0,245,0,0

In [12]:
a.sort_values("downloads",ascending=False).head()

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
0,mlg-ulb/creditcardfraud,Credit Card Fraud Detection,Anonymized credit card transactions labeled as...,Machine Learning Group - ULB,Context\n---------\n\nIt is important that cre...,3,"finance, machine learning, crime",2018-03-23 01:17:27,"Database: Open Database, Contents: Database Co...",66MB,69155632,131731,40,3052086,3323,2121
1,tmdb/tmdb-movie-metadata,TMDB 5000 Movie Dataset,"Metadata on ~5,000 movies from TMDb",The Movie Database (TMDb),### Background\nWhat can we say about the succ...,2,film,2017-09-28 01:09:12,Other (specified in description),9MB,9747156,92202,53,630515,1601,1462
2,hugomathien/soccer,European Soccer Database,"25k+ matches, players & teams attributes for E...",Hugo Mathien,The ultimate Soccer database for data analysis...,10,"europe, association football",2016-10-23 22:31:38,"Database: Open Database, Contents: Â© Original ...",34MB,36121187,80922,95,638231,1875,1458
3,lava18/google-play-store-apps,Google Play Store Apps,Web scraped data of 10k Play Store apps for an...,Lavanya Gupta,### Context\n\nWhile many public datasets (on ...,6,"internet, video games, computer science, mobil...",2019-02-03 13:55:47,Unknown,2MB,2013348,72020,37,440983,1861,313
4,zynicide/wine-reviews,Wine Reviews,"130k wine reviews with variety, location, wine...",zackthoutt,### Context\n\nAfter watching [Somm](http://ww...,4,"food and drink, critical theory",2017-11-27 17:08:04,CC BY-NC-SA 4.0,51MB,53336173,68002,24,342243,1609,1948

In [13]:
a.sort_values("discussions",inplace=False).head()

,ref,title,subtitle,creator,description,version,keywords,last_updated,license_name,size,size(bytes),downloads,discussions,views,likes,kernels
9258,melodydreamj/imagenet-file,imageNet_file,NaN,june lee,# Dataset\nThis dataset was created by june le...,1,NaN,2018-06-02 14:23:13,CC0: Public Domain,7MB,7620392,21,0,430,0,0
12322,rajesh289766/train-outliers-removed,train_outliers_removed,NaN,RAJESH,# Dataset\nThis dataset was created by RAJESH\...,1,NaN,2018-06-30 12:30:45,Unknown,2MB,1798417,9,0,387,0,0
12323,sihaodi/lgbm-seed-666,lgbm seed 666,NaN,sihao di,# Dataset\nThis dataset was created by sihao d...,1,NaN,2018-02-15 00:29:38,CC0: Public Domain,8MB,8648673,9,0,303,0,0
12324,tanmayjk/yammer,User Drop Analysis,Analysis of drop in User engagement on an appl...,Tanmay Jain,# Dataset\nThis dataset was created by Tanmay ...,2,NaN,2018-09-09 23:56:51,Unknown,5KB,5574,9,0,248,0,2
12325,pankeshpatel/handling-missing-data,handling missing data,NaN,Pankesh Patel,# Dataset\nThis dataset was created by Pankesh...,1,NaN,2019-05-18 09:37:14,Unknown,2KB,2462,9,0,75,0,1

In [15]:
a.ref

9258                       melodydreamj/imagenet-file
12322             rajesh289766/train-outliers-removed
12323                           sihaodi/lgbm-seed-666
12324                                 tanmayjk/yammer
12325              pankeshpatel/handling-missing-data
                             ...
0                             mlg-ulb/creditcardfraud
5                            ronitf/heart-disease-uci
102      kiva/data-science-for-good-kiva-crowdfunding
1                            tmdb/tmdb-movie-metadata
2                                  hugomathien/soccer
Name: ref, Length: 18518, dtype: object

In [16]:
a.ref.tail()

0                           mlg-ulb/creditcardfraud
5                          ronitf/heart-disease-uci
102    kiva/data-science-for-good-kiva-crowdfunding
1                          tmdb/tmdb-movie-metadata
2                                hugomathien/soccer
Name: ref, dtype: object

In [17]:
a["version"].value_counts()

1      14194
2       1638
3        653
4        356
5        178
       ...
296        1
93         1
205        1
265        1
220        1
Name: version, Length: 184, dtype: int64

In [18]:
a.nunique()

ref             18518
title           17681
subtitle         6836
creator         10034
description     17739
version           184
keywords         2944
last_updated    18508
license_name       26
size             2231
size(bytes)     16683
downloads        1801
discussions        39
views            4355
likes             309
kernels           236
dtype: int64

In [20]:
a["version"].nunique()

184

In [21]:
a[["version","downloads"]].nunique()

version       184
downloads    1801
dtype: int64

In [22]:
a["ref"].dtype

dtype('O')

In [23]:
n=a["version"].isnull()
n

9258     False
12322    False
12323    False
12324    False
12325    False
         ...
0        False
5        False
102      False
1        False
2        False
Name: version, Length: 18518, dtype: bool